blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/clonal-succession/discussions
    about: Please ask and answer questions here.
  - name: Project Documentation
    url: https://github.com/clonal-succession/blob/main/README.md
    about: Check out the project documentation for more information.
  - name: Web-Based Contribution Guide
    url: https://github.com/clonal-succession/blob/main/docs/github-workflow.md
    about: Learn how to contribute using only GitHub.com and VS Code on the web.