name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen
      placeholder: I'd like to see a feature that...
    validations:
      required: true
      
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: This feature would help researchers to...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
    validations:
      required: false
      
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How would you rate the impact of this feature?
      options:
        - Critical (simulation doesn't work without it)
        - High (significantly improves usability/functionality)
        - Medium (notable improvement)
        - Low (nice to have)
    validations:
      required: true
      
  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think implementing this feature would be?
      options:
        - Simple (few hours)
        - Moderate (few days)
        - Complex (week or more)
        - Not sure
    validations:
      required: false
      
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas on how to implement this feature, share them here
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here
    validations:
      required: false