name: Refactoring Proposal
description: Suggest a code refactoring that improves structure without changing functionality
title: "[REFACTOR] "
labels: ["refactoring"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a code improvement!
        
  - type: dropdown
    id: code_area
    attributes:
      label: Code Area
      description: Which part of the codebase needs refactoring?
      multiple: true
      options:
        - Core simulation
        - Cell models
        - Stem cell system
        - Physics integration
        - Visualization
        - User interface
        - Data collection
        - Other
    validations:
      required: true
      
  - type: textarea
    id: current_implementation
    attributes:
      label: Current Implementation
      description: What are the issues with the current implementation?
      placeholder: The current code has problems with...
    validations:
      required: true
      
  - type: textarea
    id: proposed_refactoring
    attributes:
      label: Proposed Refactoring
      description: How do you suggest refactoring the code?
      placeholder: I suggest restructuring this by...
    validations:
      required: true
      
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits will this refactoring bring?
      placeholder: This refactoring would improve...
    validations:
      required: true
      
  - type: textarea
    id: risks
    attributes:
      label: Potential Risks
      description: Are there any risks or potential side effects of this refactoring?
      placeholder: This might affect...
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, code snippets, or diagrams about the refactoring proposal here
    validations:
      required: false